#chris johnson cs315 Dr. Morse

#builds both with and with out heuristics
build: 
	gcc -o none none.c
	gcc -o with with.c

#runs test  both test
test_both:
	./with test.txt #operates with heuristic
	./none test.txt #operates without heuristic

#large test on both sets
large_test:
	./with large.txt
	./none large.txt

